#!/bin/bash

usage_message="$0 [-r] [-l log] [-c core] [-p pid_file] ..."

owned=
exe_dir="$( cd "$( dirname $( realpath "${BASH_SOURCE[0]}" ) )" && pwd )"

usage () {
    echo "$usage_message"
    exit 1
}

parse_opt () {
    long=$1
    short=$2
    opt=$3
    next=$4
    ret=0

    var=$(echo "$long" | sed -e 's/[^-a-zA-Z_0-9]//g' -e 's/-/_/g')
    val=

    if [ "$opt" != "--${!long}" ]; then
        val=$(echo "$opt" | sed -r "s/(-$short|--$long=)//")
    fi
    if [ -z "$val" ]; then
        val=$next
        ret=1
    fi

    eval "$var=\"$val\""
    return $ret
}

gdb_cmds=
term=
pid_file=
core=
log=
while (( "$#" )); do
    case $1 in
        -r)
            gdb_cmds="${gdb_cmds}r
"
            ;;
        -t*|--term=*|--term)
            if ! parse_opt term t $@; then
                shift
            fi
            ;;
        -l*|--log=*|--log)
            if ! parse_opt log l $@; then
                shift
            fi
            ;;
        -p*|--pid-file=*|--pid-file)
            if ! parse_opt pid-file p $@; then
                shift
            fi
            ;;
        -c*|--core=*|--core)
            if ! parse_opt core c $@; then
                shift
            fi
            ;;
        *)
            break ;;
    esac
    shift
done
if (( ! "$#" )); then usage; fi

launch () {
    if [ -n "$term" ]; then
        parent=$($exe_dir/daemon $term -e "$@")
        pid=
        while [ -z "$pid" ]; do pid=$(pgrep -P $parent); done
        owned="$owned $parent"
        pts="/dev/$(ps -o tty= --pid=$pid)"
    else
        this_tty=$(ps -o tty= --pid $$)
        this_pane=$(tmux list-panes -F '#{pane_tty} #{pane_id}' | grep "$this_tty" | awk '{ print $2 }')
        tmux select-pane -t $this_pane
        cmd=
        for arg in "$@"; do
            cmd="$cmd \"$arg\""
        done
        if [ -z "$horizontal" ]; then
            tmux split-window -p 30 "$cmd"
            tmux swap-pane -s $this_pane
        else
            tmux split-window -h -p 30 "$cmd"
            tmux swap-pane -s $this_pane
        fi
        new_pane=$(tmux list-panes -F '#{?pane_active,active,} #{pane_pid} #{pane_tty} #{pane_id}' | grep active | awk '{ print $2, $3 }')
        owned="$owned $(echo $new_pane | awk '{ print $1 }')"
        pts=$(echo $new_pane | awk '{ print $2 }')
    fi
}

current_pane=$(tmux list-panes -F '#{?pane_active,active,} #{pane_id}' | grep active | awk '{ print $2 }')

if [ -z "$EXTERMINATOR_FILE" ]; then
    export EXTERMINATOR_FILE=$(mktemp)
    horizontal=1 launch vim -c "let g:session_autoload='no'" -c "let g:exterminator_file='$EXTERMINATOR_FILE'"
fi

export VIM_TMUX_PANE=$(tmux list-panes -F '#{?pane_active,active,} #{pane_id}' | grep active | awk '{ print $2 }')

launch $exe_dir/signal-passer $$

if [ -n "$log" ]; then
    cat $log > $pts
else
    echo Debugging in $(pwd): $@ > $pts
    echo > $pts
fi

tmux select-pane -t $current_pane

gdb_file=$(mktemp)
echo "tty $pts" >> $gdb_file
if [ -n "$pid_file" ]; then
    echo "define hookpost-run" >> $gdb_file
    echo "echo running" >> $gdb_file
    echo "python open('$pid_file', 'w').write(str(gdb.selected_inferior().pid))" >> $gdb_file
    echo "end" >> $gdb_file
fi
echo $gdb_cmds >> $gdb_file

clear
if [ -z "$core" ]; then
    gdb -x $exe_dir/exterminator.py -x $gdb_file -args "$@"
else
    gdb -x $exe_dir/exterminator.py -x $gdb_file -core $core "$@"
fi

kill $owned 2>/dev/null

rm $EXTERMINATOR_FILE
rm $gdb_file

